---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: company
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 4001
    targetPort: 4000
...