apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
        - name: report
          image: europe-west3-docker.pkg.dev/quixotic-market-402317/cloud-project-registry/cloud-project-report:v0.2
          ports:
          - containerPort: 4000
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: CLIENT_SECRET
      imagePullSecrets:
      - name: regcred