---
apiVersion: v1
kind: Service
metadata:
  name: administration-service
  namespace: company
spec:
  type: ClusterIP
  selector:
    app: administration-service
  ports:
  - protocol: TCP
    port: 4002
    targetPort: 4000
...