---
apiVersion: v1
kind: Service
metadata:
  name: report-service
  namespace: company
spec:
  type: ClusterIP
  selector:
    app: report-service
  ports:
  - protocol: TCP
    port: 4003
    targetPort: 4000
...