name: Build/Destroy gke Infrastructure

# trigger manually
on:
  workflow_dispatch:
    inputs:
      tf:
        description: "Bulild/Destroy"
        required: true
        default: "build"
        type: choice
        options:
          - build
          - destroy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0

      - id: init
        name: Terraform init
        run: |
          cd ./terraform
          terraform init

      - id: run
        name: Terraform apply/destroy
        run: |
          cd ./terraform
          if [[ "${{ github.event.inputs.tf }}" == "build" ]]; then
              terraform apply -auto-approve
          elif [[ "${{ github.event.inputs.tf }}" == "destroy" ]]; then
              terraform destroy -auto-approve
          fi

      - run: echo ${{ steps.run.outputs.stdout }}
      - run: echo ${{ steps.run.outputs.stderr }}
      - run: echo ${{ steps.run.outputs.exitcode }}
